#!/usr/bin/env bash


# HELPER FUNCTIONS ============================================================

_source_if_exists() {
  if [ -f $1 ]; then
    . $1
    eval $2
  fi
}



# ALIASES =====================================================================

# shortcuts for the most commonly used tools
alias be='bundle exec'
alias v='vim'
alias g='git'
alias gst='git status'
alias gap='git add -p'

# attach to the tmux session or create a new named after the user
alias t='tmux attach-session -t "$(whoami)" || tmux new-session -s "$(whoami)"'

# update all Vim plugins
alias vundle='vim +PluginInstall! +qall'

# override common tools with useful arguments
alias grep='grep --color'
alias ls='ls -FG'
alias la='ls -lah'



# VARIABLES ===================================================================

# normalize the PATH stack
export PATH='/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin'

# prepend our shared scripts to the PATH so they take priority
export PATH="$HOME/.buffet/bin:$PATH"

# set the default editor to Vim
export EDITOR=vim
export VISUAL=vim



# AUTO-COMPLETES ==============================================================

# source any homebrew-supplied autocompletion files
comps_dir='/usr/local/etc/bash_completion.d'

if [ -d $comps_dir ]; then
  for file in $(command ls $comps_dir); do
    . "$comps_dir/$file"
  done
fi



# OTHER SOURCED FILES =========================================================

_source_if_exists "$HOME/.prompt"
_source_if_exists "$HOME/.bashrc.local"
