#!/usr/bin/env bash
#   ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#   ┃                                   ┃
#   ┃   ____         __  __      _      ┃
#   ┃  | __ ) _   _ / _|/ _| ___| |_    ┃
#   ┃  |  _ \| | | | |_| |_ / _ \ __|   ┃
#   ┃  | |_) | |_| |  _|  _|  __/ |_    ┃
#   ┃  |____/ \__,_|_| |_|  \___|\__|   ┃
#   ┃                                   ┃
#   ┃        By Bendyworks - 2018       ┃
#   ┃                                   ┃
#   ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
#
# FUNCTIONS ===================================================================
source_if_exists() { if [ -f $1 ]; then . $1; eval $2; fi; }
source_if_exists "$HOME/.buffet/functions"

# VARIABLES ===================================================================
source_if_exists "$HOME/.buffet/path"
source_if_exists "$HOME/.buffet/variables"

# ALIASES =====================================================================
source_if_exists "$HOME/.buffet/aliases"

# AUTO-COMPLETION =============================================================
source_if_exists "$HOME/.buffet/auto-complete"
source_if_exists "$HOME/.buffet/npm-auto-complete"

# OTHER SOURCED FILES =========================================================
source_if_exists "$HOME/.pair"            # "pair() shell function to set Git pairs"
source_if_exists "$HOME/.bashrc.local"    # local .bashrc overrides
source_if_exists "$HOME/.prompt"          # Bash prompt

# EOF =========================================================================
