#!/usr/bin/env bash


# HELPER FUNCTIONS ============================================================

_source_if_exists() {
  if [ -f $1 ]; then
    . $1
    eval $2
  fi
}



# VARIABLES ===================================================================

# normalize the PATH stack
export PATH='/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin'

# additional paths
export PATH="$PATH:$HOME/.rvm/bin"    # append RVM bins
export PATH="$HOME/.buffet/bin:$PATH" # prepend Bendyworks bins

# set the default editor to Vim
export EDITOR=vim
export VISUAL=vim

# not used by any program, but nice to reference
export PG_DATA_DIR='/usr/local/var/postgres'



# ALIASES =====================================================================

# shortcuts for the most commonly used tools
alias be='bundle exec'
alias v='vim'
alias g='git'
alias gr='grunt'
alias r='rake'

# override common tools with useful arguments
alias grep='grep --color'
alias ls='ls -FG'
alias la='ls -lah'

# Git aliases adopted by seemingly every dev shop
alias gst='git status'
alias gap='git add -p'

# make Postgres not a huge PITA to start/stop
alias pgup="pg_ctl -D $PG_DATA_DIR -l $PG_DATA_DIR/server.log start"
alias pgdown="pg_ctl -D $PG_DATA_DIR stop"

# run a server in the current directory
alias server='ruby -run -e httpd . -p 9090'

# attach to the tmux session or create a new named after the user
alias t='tmux attach-session -t "$(whoami)" || tmux new-session -s "$(whoami)"'

# update all Vim plugins
alias vundle='vim +PluginInstall! +qall'



# FUNCTIONS ===================================================================

# creates a directory and then immediately moves you to that directory
take() {
  mkdir -p $1;
  cd $1
}



# AUTO-COMPLETES ==============================================================

# source any homebrew-supplied autocompletion files
comps_file='/usr/local/etc/bash_completion'

if [ -f $comps_file ]; then
  . $comps_file
fi

# use git autocompletion when "git" is aliased to "g"
if type __git_complete &>/dev/null; then
  __git_complete g __git_main
fi



# OTHER SOURCED FILES =========================================================

_source_if_exists "$HOME/.pair"            # "pair() shell function to set Git pairs"
_source_if_exists "$HOME/.rvm/scripts/rvm" # required by RVM
_source_if_exists "$HOME/.bashrc.local"    # local .bashrc overrides
_source_if_exists "$HOME/.prompt"          # Bash prompt
