#!/usr/bin/env bash

# GENERAL SHELL ====================================================================================

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"
# output path entries on separate lines
alias path='echo $PATH | tr -s ":" "\n"'
# export each item in a .env file
alias read_env='export $(grep -v "^#" .env | xargs -0)'

# NAVIGATION =======================================================================================

alias ..='cd ..' # ':' is reserved in bash as equivalent to true
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias ::='cd ../..'
alias :::='cd ../../..'
alias ::::='cd ../../../..'
alias :::::='cd ../../../../..'

# COMMON ===========================================================================================

# shortcuts for the most commonly used tools
alias b='bundle'
alias be='bundle exec'
alias v='vim'
alias gr='grunt'
alias r='rake'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU
  colorflag="--color"
  # export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # MacOS
  colorflag="-G"
  # export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

# List all files colorized in long format
alias l="ls -lF ${colorflag}"

# List all files colorized in long format, excluding . and ..
alias laf="ls -lAF ${colorflag}"

# Always use color output for `ls`
alias ls="command ls ${colorflag}"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto --exclude-dir=.svn --exclude-dir=.git --exclude-dir=tmp'
alias fgrep='fgrep --color=auto --exclude-dir=.svn --exclude-dir=.git --exclude-dir=tmp'
alias egrep='egrep --color=auto --exclude-dir=.svn --exclude-dir=.git --exclude-dir=tmp'

alias la='ls -lah ${colorflag}'
alias ll='ls -l ${colorflag}'
alias ls='ls -FG ${colorflag}'

# List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

alias psack='ps aux | grep'

# GIT ==============================================================================================

alias g='git'
alias ga='git add'
alias gap='git add -p'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit -v'
alias gc!='git commit -v --amend'
alias gca='git commit -v -a'
alias gca!='git commit -v -a --amend'
alias gco='git checkout'
alias gcm='git checkout master'
alias gcl='git config --list'
alias gd='git diff'
alias gdc='git diff --cached'
alias gst='git status'
alias gss='git status -s'
alias gl='git pull'
alias gup='git pull --rebase'
alias gp='git push'

# DEVELOPMENT ======================================================================================

# make Postgres not a huge PITA to start/stop
alias pgup="pg_ctl -D $PG_DATA_DIR -l $PG_DATA_DIR/server.log start"
alias pgdown="pg_ctl -D $PG_DATA_DIR stop"

# run a server in the current directory
alias server='ruby -run -e httpd . -p 9090'

# attach to the tmux session or create a new session named after the user
alias tmuxup='tmux attach-session -t "$(whoami)" || tmux new-session -s "$(whoami)"'

# update Vim plugins
alias vundle='vim +PluginInstall! +qall'

# NETWORKING =======================================================================================

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"
# External IP Address
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
# Local IP Address
alias localip="ipconfig getifaddr en0"
# IP Addresses
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# EOF ==============================================================================================
