#!/usr/bin/env bash

# create a directory and immediately move to that directory
take() { mkdir -p $1; cd $1; }

# Heroku Helper: `prod heroku [cmd] [opts]`
prod() { $* --app $(basename $(pwd))-production; }

# Nuke NPM Node Modules and reinstall
npmnuke() { rm -rf node_modules && npm install; }

brewyolo() {
  brew update && \
  brew outdated && \
  brew upgrade && \
  brew postgresql-upgrade-database || brew cleanup
}

# Determine size of a file or total size of a directory
function fs() {
  if du -b /dev/null > /dev/null 2>&1; then
    local arg=-sbh;
  else
    local arg=-sh;
  fi
  if [[ -n "$@" ]]; then
    du $arg -- "$@";
  else
    du $arg .[^.]* ./*;
  fi;
}

# Determine whether an array contains a string
function contains() {
  local n=$#
  local value=${!n}
  for ((i=1;i < $#;i++)) {
    if [ "${!i}" == "${value}" ]; then
      echo "y"
      return 0
    fi
  }
  echo "n"
  return 1
}

# Create a data URL from a file
function dataurl() {
  local mimeType=$(file -b --mime-type "$1");
  if [[ $mimeType == text/* ]]; then
    mimeType="${mimeType};charset=utf-8";
  fi
  echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}
