#!/usr/bin/env bash

# normalize the PATH stack
export PATH='/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin'

# Buffet bins
prepend_to_path "$HOME/.buffet/bin"

# Android SDK
if [ -d "$HOME/Library/Android/sdk" ]; then
  export ANDROID_HOME="$HOME/Library/Android/sdk"
  prepend_to_path "$ANDROID_HOME/platform-tools"
  prepend_to_path "$ANDROID_HOME/tools"
fi

# Node Version Manager
if [ -d "$HOME/.nvm" ]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi


# Ruby Version Manager
if [ -d "$HOME/.rvm" ]; then
  prepend_to_path "$HOME/.rvm/bin"
  source_if_exists "$HOME/.rvm/scripts/rvm"
fi

# RBENV
if hash rbenv 2>/dev/null; then
  eval "$(rbenv init -)"
fi
