#!/usr/bin/env bash

# set vim as the default editor
export EDITOR=vim
export VISUAL=vim

# not used by any program, but nice to reference
export PG_DATA_DIR='/usr/local/var/postgres'

# ignore common large directories in grep
export GREP_OPTIONS='--exclude-dir=.svn --exclude-dir=.git --exclude-dir=tmp'
